# Generated by Django 4.0.3 on 2022-06-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_source_alter_category_options_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
