# Generated by Django 4.0.3 on 2023-05-25 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='owner',
        ),
    ]
